//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bought
    {
        public int IdItem { get; set; }
        public int IdSeller { get; set; }
        public int NumberOfItems { get; set; }
        public string Type { get; set; }
        public double Price { get; set; }
        public System.DateTime Date { get; set; }
    }
}
